name: volunteerapp
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
